name: Node CI

on: [push]

jobs:
  build:
    name: Lint & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
      - run: yarn xo
      - run: yarn build