on:
  push:
    paths:
      ["src/stories/**", "src/Line/**", "src/Word/**", "src/TextAssembler/**"]

name: Storybook Deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: borales/actions-yarn@v2.3.0
      - name: Checkout
        uses: actions/checkout@master
      - name: Install packages
        run: yarn install
      - name: Build
        run: yarn build-storybook
      - name: Deploy to storybook-static branch
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: storybook-static
          folder: storybook-static
