on: 
  push:
    paths: ["src/stories/**", "src/components/**"]


name: Storybook Deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and deploy to storybook-static branch
      uses: JamesIves/github-pages-deploy-action@2.0.3
      uses: borales/actions-yarn@v2.3.0
      env:
        BRANCH: storybook-static
        FOLDER: storybook-static
        BUILD_SCRIPT: yarn install && yarn build-storybook